class CfgPatches
{
	class 20ABCT_infantry
	{
		name="20th ABCT Infantry";
		units[]=
		{
			"20ABCT_Sect_Comd",
			"20ABCT_Sect_C_Rfn",
			"20ABCT_Sect_C_TM",
			"20ABCT_Sect_C_PM",
			"20ABCT_Sect_2IC",
			"20ABCT_Sect_D_TM",
			"20ABCT_Sect_D_SS",
			"20ABCT_Sect_D_GPMG",
			"20ABCT_Pl_Comd",
			"20ABCT_Pl_Sjt",
			"20ABCT_Pl_WR_Sjt",
			"20ABCT_Pl_CMT",
			"20ABCT_Pl_Rnr",
			"20ABCT_AFV_Crew"
		};
		weapons[]={};
		requiredAddons[]=
		{
			"20ABCT_core",
			"20ABCT_weapons"
		};
		author="20th ABCT Mod Development Team";
	};
};

class cfgGroups
{
	class WEST
	{
		name="BLUFOR";
		class ABCT
		{
			name="20th ABCT";
			class Infantry
			{
				name="Light Role Infantry";
				class 20ABCT_B_HQ_Section_Light_Role
				{
					name="HQ Section";
					faction="20ABCT";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="20ABCT_Pl_Comd";
						rank="LIEUTENANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="20ABCT_Pl_Sjt";
						rank="SERGEANT";
						position[]={2,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="20ABCT_Pl_CMT";
						rank="CORPORAL";
						position[]={4,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="20ABCT_Pl_Rnr";
						rank="PRIVATE";
						position[]={0,-2,0};
					};
					class Unit4
					{
						side=1;
						vehicle="20ABCT_Pl_Rnr";
						rank="PRIVATE";
						position[]={2,-2,0};
					};
				};
				class 20ABCT_B_Rifle_Section_LR
				{
					name="Rifle Section";
					faction="20ABCT";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="20ABCT_Sect_Comd";
						rank="CORPORAL";
						position[]={2,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="20ABCT_Sect_C_PM";
						rank="PRIVATE";
						position[]={0,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="20ABCT_Sect_C_TM";
						rank="PRIVATE";
						position[]={4,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="20ABCT_Sect_C_Rfn";
						rank="PRIVATE";
						position[]={6,0,0};
					};
					class Unit4
					{
						side=1;
						vehicle="20ABCT_Sect_D_TM";
						rank="PRIVATE";
						position[]={0,-2,0};
					};
					class Unit5
					{
						side=1;
						vehicle="20ABCT_Sect_2IC";
						rank="CORPORAL";
						position[]={2,-2,0};
					};
					class Unit6
					{
						side=1;
						vehicle="20ABCT_Sect_D_SS";
						rank="PRIVATE";
						position[]={4,-2,0};
					};
					class Unit7
					{
						side=1;
						vehicle="20ABCT_Sect_D_GPMG";
						rank="PRIVATE";
						position[]={6,-2,0};
					};
				};
			};
			class Mechanized
			{
				name="Armoured Infantry";
				class 20ABCT_B_HQ_Section_AI
				{
					name="HQ Section";
					faction="20ABCT";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="20ABCT_Pl_Sjt";
						rank="SERGEANT";
						position[]={4,2,0};
					};
					class Unit1
					{
						side=1;
						vehicle="20ABCT_Pl_CMT";
						rank="CORPORAL";
						position[]={4,0,0};
					};
					class Unit2
					{
						side=1;
						vehicle="20ABCT_Pl_Rnr";
						rank="PRIVATE";
						position[]={4,-2,0};
					};
					class Unit3
					{
						side=1;
						vehicle="20ABCT_Pl_Rnr";
						rank="PRIVATE";
						position[]={4,-4,0};
					};
					class Unit4
					{
						side=1;
						vehicle="20ABCT_fv510_warrior_ai_dep";
						rank="MAJOR";
						position[]={0,0,0};
					};
				};
				class 20ABCT_B_Rifle_Section_AI
				{
					name="Rifle Section";
					faction="20ABCT";
					side=1;
					class Unit0
					{
						side=1;
						vehicle="20ABCT_fv510_warrior_ai_dep";
						rank="MAJOR";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="20ABCT_Sect_Comd";
						rank="PRIVATE";
						position[]={4,2,0};
					};
					class Unit2
					{
						side=1;
						vehicle="20ABCT_Sect_C_TM";
						rank="PRIVATE";
						position[]={4,0,0};
					};
					class Unit3
					{
						side=1;
						vehicle="20ABCT_Sect_C_PM";
						rank="PRIVATE";
						position[]={4,-2,0};
					};
					class Unit4
					{
						side=1;
						vehicle="20ABCT_Sect_2IC";
						rank="CORPORAL";
						position[]={4,-4,0};
					};
					class Unit5
					{
						side=1;
						vehicle="20ABCT_Sect_D_TM";
						rank="PRIVATE";
						position[]={4,-6,0};
					};
					class Unit6
					{
						side=1;
						vehicle="20ABCT_Sect_D_SS";
						rank="PRIVATE";
						position[]={4,-8,0};
					};
				};
			};
		};
	};
};

class CfgVehicles
{
	class B_officer_F;
	class TRF_TRIZIP_LR;
	class B_Soldier_SL_F;
	class B_medic_F;
	class B_Carryall_mcamo;
	class B_Soldier_F;
	class B_Carryall_oli;
	class B_crew_F;
	class B_AssaultPack_cbr;
	class TRF_VIRTUS_ASSAULT_PACK_LR;
	class TRF_VIRTUS_ASSAULT_PACK;
	class TRF_TRIZIP;
	class B_Kitbag_mcamo;
	class B_Kitbag_sgg;
	class B_Soldier_TL_F;
	class B_Kitbag_rgr;
	class B_soldier_M_F;
	class B_Kitbag_cbr;
	class B_HeavyGunner_F;

	class 20ABCT_Pl_Comd: B_officer_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Platoon Commander";
		uniformClass="20X_RIFLES_1";
		weapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_Grippod_T_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS_PiPUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_Grippod_T_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS_PiPUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"ACRE_PRC117F",
			"H2H_acc_bayo_L3A1"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"ACRE_PRC117F",
			"H2H_acc_bayo_L3A1"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC_3",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC_3",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Pl_Comd_pack";
	};
	class 20ABCT_Pl_Sjt: B_Soldier_SL_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Platoon Serjeant";
		uniformClass="20X_RIFLES_7";
		weapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"ACRE_PRC117F",
			"H2H_acc_bayo_L3A1"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"ACRE_PRC117F",
			"H2H_acc_bayo_L3A1"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_3",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_3",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Pl_Sjt_pack";
	};
	class 20ABCT_Pl_CMT: B_medic_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Platoon CMT";
		uniformClass="20X_RAMS_3";
		weapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_afg_d",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_afg_d",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"rhsusf_ANPVS_15",
			"H2H_acc_bayo_L3A1",
			"kat_MFAK",
			"afuk_beret3_ramc",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_salineIV_250",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"rhsusf_ANPVS_15",
			"H2H_acc_bayo_L3A1",
			"kat_MFAK",
			"afuk_beret3_ramc",
			"ACRE_PRC152",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_packingBandage",
			"ACE_epinephrine",
			"ACE_morphine",
			"ACE_salineIV_250",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Medic",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Medic",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Pl_CMT_pack";
	};
	class 20ABCT_Pl_Rnr: B_Soldier_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Platoon Runner";
		uniformClass="20X_RIFLES_6";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Pl_Rnr_pack";
	};
	class 20ABCT_AFV_Crew: B_crew_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_AI";
		side=1;
		displayName="AFV Crew";
		uniformClass="20X_RIFLES_2";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_afg_d",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_afg_d",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Crew",
			"rhsusf_shemagh2_gogg_grn"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Crew",
			"rhsusf_shemagh2_gogg_grn"
		};
		backpack="20ABCT_AFV_Crew_pack";
	};
	class 20ABCT_Pl_WR_Sjt: B_Soldier_SL_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_AI";
		side=1;
		displayName="Warrior Serjeant";
		uniformClass="20X_RIFLES_7";
		weapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"Laserdesignator_03",
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"Laserbatteries",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhsusf_mag_17Rnd_9x19_FMJ",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC_2",
			"rhsusf_shemagh2_gogg_tan"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"Laserdesignator_03",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC_2",
			"rhsusf_shemagh2_gogg_tan"
		};
		backpack="20ABCT_Pl_WR_Sjt_pack";
	};
	class 20ABCT_Sect_Comd: B_Soldier_SL_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Section Commander";
		uniformClass="20X_RIFLES_4";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UGL_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UGL_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_IC",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_Comd_pack";
	};
	class 20ABCT_Sect_C_PM: B_Soldier_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Pointman";
		uniformClass="20X_RIFLES_1";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_Flashlight_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_2",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_2",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_C_PM_pack";
	};
	class 20ABCT_Sect_C_TM: B_Soldier_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Team Medic (Charlie)";
		uniformClass="20X_RIFLES_5";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_2",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_2",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_C_TM_pack";
	};
	class 20ABCT_Sect_C_Rfn: B_Soldier_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Rifleman";
		uniformClass="20X_RIFLES_8";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_C_Rfn_pack";
	};
	class 20ABCT_Sect_2IC: B_Soldier_TL_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Section 2IC";
		uniformClass="20X_RIFLES_6";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UGL_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UGL_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDS",
			"rhsusf_weap_glock17g4",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"ACRE_PRC152",
			"rhsusf_ANPVS_15",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_1Rnd_HEDP_Grenade_Shell",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Grenadier",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Grenadier",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_2IC_pack";
	};
	class 20ABCT_Sect_D_TM: B_Soldier_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Team Medic (Delta)";
		uniformClass="20X_RIFLES_7";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L85A3_UK3CB_BAF_LLM_IR_TanRKSL_optic_LDSUK3CB_underbarrel_acc_grippod_t",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_3",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Rifleman_3",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_D_TM_pack";
	};
	class 20ABCT_Sect_D_SS: B_soldier_M_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="Sharpshooter";
		uniformClass="20X_RIFLES_3";
		weapons[]=
		{
			"20ABCT_UK3CB_BAF_L129A1_UK3CB_BAF_LLM_IR_TanUK3CB_BAF_TA648_308UK3CB_underbarrel_acc_fgrip_bipod",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"20ABCT_UK3CB_BAF_L129A1_UK3CB_BAF_LLM_IR_TanUK3CB_BAF_TA648_308UK3CB_underbarrel_acc_fgrip_bipod",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd_T",
			"UK3CB_BAF_762_L42A1_20Rnd_T",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd",
			"UK3CB_BAF_762_L42A1_20Rnd_T",
			"UK3CB_BAF_762_L42A1_20Rnd_T",
			"UK3CB_BAF_762_100Rnd",
			"UK3CB_BAF_762_100Rnd",
			"rhs_mag_m67",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Sharpshooter",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Sharpshooter",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Set_D_SS_pack";
	};
	class 20ABCT_Sect_D_GPMG: B_HeavyGunner_F
	{
		faction="20ABCT";
		editorSubcategory="20ABCT_LRI";
		side=1;
		displayName="GPMG Gunner";
		uniformClass="20X_RIFLES_1";
		weapons[]=
		{
			"UK3CB_BAF_L7A2",
			"Put",
			"Throw"
		};
		respawnWeapons[]=
		{
			"UK3CB_BAF_L7A2",
			"Put",
			"Throw"
		};
		items[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		respawnItems[]=
		{
			"ACE_Chemlight_Shield",
			"ACE_Chemlight_Shield",
			"ACE_EarPlugs",
			"ACE_MapTools",
			"ACE_fieldDressing",
			"ACE_packingBandage",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACRE_PRC343",
			"afuk_beret1_rifles",
			"H2H_acc_bayo_L3A1",
			"rhsusf_ANPVS_14"
		};
		magazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_200Rnd",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_200Rnd",
			"UK3CB_BAF_762_200Rnd"
		};
		respawnMagazines[]=
		{
			"Chemlight_red",
			"Chemlight_red",
			"rhs_mag_m67",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_200Rnd",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_SmokeShellGreen",
			"UK3CB_BAF_762_200Rnd",
			"UK3CB_BAF_762_200Rnd"
		};
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Gunner",
			"rhs_googles_yellow"
		};
		respawnLinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemGPS",
			"TRF_BATLSKIN_REVISION_SCRIM_OAK",
			"TRF_STV_Gunner",
			"rhs_googles_yellow"
		};
		backpack="20ABCT_Sect_D_GPMG_pack";
	};
	class 20ABCT_Pl_Comd_pack: TRF_TRIZIP_LR
	{
		scope=1;
		class TransportMagazines
		{
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_ACRE_PRC117F
			{
				count=1;
				name="ACRE_PRC117F";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Pl_Sjt_pack: TRF_TRIZIP_LR
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_ACRE_PRC117F
			{
				count=1;
				name="ACRE_PRC117F";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Pl_CMT_pack: B_Carryall_mcamo
	{
		scope=1;
		class TransportMagazines
		{
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_kat_MFAK
			{
				count=1;
				name="kat_MFAK";
			};
			class _xx_afuk_beret3_ramc
			{
				count=1;
				name="afuk_beret3_ramc";
			};
			class _xx_ACRE_PRC152
			{
				count=1;
				name="ACRE_PRC152";
			};
			class _xx_ACE_fieldDressing
			{
				count=3;
				name="ACE_fieldDressing";
			};
			class _xx_ACE_packingBandage
			{
				count=4;
				name="ACE_packingBandage";
			};
			class _xx_ACE_morphine
			{
				count=3;
				name="ACE_morphine";
			};
			class _xx_ACE_tourniquet
			{
				count=3;
				name="ACE_tourniquet";
			};
			class _xx_ACE_epinephrine
			{
				count=1;
				name="ACE_epinephrine";
			};
			class _xx_ACE_salineIV_250
			{
				count=1;
				name="ACE_salineIV_250";
			};
			class _xx_ACE_splint
			{
				count=2;
				name="ACE_splint";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Pl_Rnr_pack: B_Carryall_oli
	{
		scope=1;
		class TransportMagazines
		{
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_AFV_Crew_pack: B_AssaultPack_cbr
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Pl_WR_Sjt_pack: TRF_VIRTUS_ASSAULT_PACK_LR
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_Comd_pack: TRF_VIRTUS_ASSAULT_PACK_LR
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_1Rnd_HEDP_Grenade_Shell
			{
				count=11;
				magazine="UK3CB_BAF_1Rnd_HEDP_Grenade_Shell";
			};
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=1;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_C_PM_pack: TRF_TRIZIP
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=1;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_C_TM_pack: TRF_VIRTUS_ASSAULT_PACK
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=1;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
			class _xx_ACE_fieldDressing
			{
				count=2;
				name="ACE_fieldDressing";
			};
			class _xx_ACE_packingBandage
			{
				count=2;
				name="ACE_packingBandage";
			};
			class _xx_ACE_morphine
			{
				count=2;
				name="ACE_morphine";
			};
			class _xx_ACE_tourniquet
			{
				count=2;
				name="ACE_tourniquet";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_C_Rfn_pack: B_Kitbag_sgg
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=1;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_2IC_pack: TRF_VIRTUS_ASSAULT_PACK_LR
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_1Rnd_HEDP_Grenade_Shell
			{
				count=11;
				magazine="UK3CB_BAF_1Rnd_HEDP_Grenade_Shell";
			};
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=2;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_rhsusf_ANPVS_15
			{
				count=1;
				name="rhsusf_ANPVS_15";
			};
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_D_TM_pack: B_Kitbag_rgr
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=2;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
			class _xx_ACE_fieldDressing
			{
				count=2;
				name="ACE_fieldDressing";
			};
			class _xx_ACE_packingBandage
			{
				count=2;
				name="ACE_packingBandage";
			};
			class _xx_ACE_morphine
			{
				count=2;
				name="ACE_morphine";
			};
			class _xx_ACE_tourniquet
			{
				count=2;
				name="ACE_tourniquet";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Set_D_SS_pack: B_Kitbag_cbr
	{
		scope=1;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_762_100Rnd
			{
				count=2;
				magazine="UK3CB_BAF_762_100Rnd";
			};
			class _xx_rhs_mag_m67
			{
				count=2;
				magazine="rhs_mag_m67";
			};
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
		};
		class TransportWeapons
		{
		};
	};
	class 20ABCT_Sect_D_GPMG_pack: TRF_TRIZIP
	{
		scope=1;
		scopeCurator=0;
		scopeArsenal=0;
		class TransportMagazines
		{
			class _xx_UK3CB_BAF_SmokeShellGreen
			{
				count=2;
				magazine="UK3CB_BAF_SmokeShellGreen";
			};
			class _xx_UK3CB_BAF_762_200Rnd
			{
				count=2;
				magazine="UK3CB_BAF_762_200Rnd";
			};
		};
		class TransportItems
		{
			class _xx_afuk_beret1_rifles
			{
				count=1;
				name="afuk_beret1_rifles";
			};
			class _xx_H2H_acc_bayo_L3A1
			{
				count=1;
				name="H2H_acc_bayo_L3A1";
			};
			class _xx_rhsusf_ANPVS_14
			{
				count=1;
				name="rhsusf_ANPVS_14";
			};
		};
		class TransportWeapons
		{
		};
	};
};
