name = "20ABCT"
prefix = "20ABCT"
author = "Keown"

mainprefix = "z"

[version]
path = "addons/core/script_version.hpp"
git_hash = 0


[hemtt.launch.default]
workshop = [
    "450814997",
    "463939057",
    "3407948300",
    "3365663203",
    "2094487581",
    "1755268799",
    "893349825"
]

mission = "20abct.Stratis"
